project:
  name: cic-yang
  description: CIC YANG building blocks — IETF és OpenConfig YANG modellek CIC-be
    illesztett, újrafelhasználható schema fragmentek adapter kompozícióhoz
  license: CC-BY-NC-SA-4.0
  main_branch: yang/main
  owner: Gabor Zoltan Sinko
  maintenance:
    status: active
    supported_until: '2027-12-31'
  contacts:
    - type: email
      value: sinkog@centralinfracore.hu
  links:
    - name: repository
      url: https://github.com/CentralInfraCore/cic-yang.git
compiler_settings:
  meta_schemas_dir: ./
  source_dir: schemas
  meta_schema_file: md.meta.schema.yaml
  primitive_schema_file: schemas/index.yaml
  vault_key_name: cic-my-sign-key
x-cic:
  repo_type: yang-layer
  base_primitive: cic-primitives@v0.1.2
release:
  version: 0.0.dev
