project:
  name: cic-yang
  description: CIC YANG building blocks — IETF és OpenConfig YANG modellek CIC-be
    illesztett, újrafelhasználható schema fragmentek adapter kompozícióhoz
  license: CC-BY-NC-SA-4.0
  main_branch: yang/main
  owner: Gabor Zoltan Sinko
  maintenance:
    status: active
    supported_until: '2027-12-31'
  contacts:
    - type: email
      value: sinkog@centralinfracore.hu
  links:
    - name: repository
      url: https://github.com/CentralInfraCore/cic-yang.git
compiler_settings:
  meta_schemas_dir: ./
  source_dir: schemas
  meta_schema_file: md.meta.schema.yaml
  primitive_schema_file: schemas/index.yaml
  vault_key_name: cic-my-sign-key
x-cic:
  repo_type: yang-layer
  base_primitive: cic-primitives@v0.1.2
release:
  version: 0.1.1
  timestamp: '2026-05-07T13:47:29.013571+00:00'
  repository_tree_hash: Li/gzWvxboXrGy/zAWt6yy5PDjt2gs0oZxJqYCA4LmM=
  build_hash: mnWnRmGrY0R1LW1mwl6JBrZiiE1mSW5wnBHuWM2nBA0=
  sign: vault:v1:MEQCIC0/wmRbmHXl16I46qjfsFX4GtkrIn4xcvxABaBq+clAAiBxMN3rd3R82rlZPyLjH70//WvCp9hWGdjxSmFe4sauzQ==
  cert: '-----BEGIN CERTIFICATE-----

    MIICBjCCAaygAwIBAgIUSnRMR6RPnEbg296XWPOqq/u5PCwwCgYIKoZIzj0EAwIw

    QzELMAkGA1UEBhMCSFUxGTAXBgNVBAoMEENlbnRyYWxJbmZyYUNvcmUxGTAXBgNV

    BAMMEENJQyBEZXZlbG9wZXIgQ0EwHhcNMjYwMzIwMTMyMjU5WhcNMjYxMjMxMTMy

    MjU5WjBFMQswCQYDVQQGEwJIVTEZMBcGA1UECgwQQ2VudHJhbEluZnJhQ29yZTEb

    MBkGA1UEAwwSR2Fib3IgWm9sdGFuIFNpbmtvMFkwEwYHKoZIzj0CAQYIKoZIzj0D

    AQcDQgAEIG2CVmTfmLB9pLLclj7YmP2eedAjklpy4LGrU2ijoiy6Xqpuybv7OgJe

    i+ez31s65NEV8+X/ByeX1cstR988z6N8MHowCQYDVR0TBAIwADAdBgNVHQ4EFgQU

    yZN6AIX/TNnIJ9GwAa/NRN3ujHAwHwYDVR0jBBgwFoAUXn6CHYzPUqU4JVP8g+OS

    WeDYjhcwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF

    BQcDBDAKBggqhkjOPQQDAgNIADBFAiEA+bFzXRoJ4PCQbhAAtpkcMjt0vNj5rEW0

    lOMBGDNyaWkCIB1vmM7PcZzv/c9bIrxF5kqv6QXomouhByUfeNUTbpKW

    -----END CERTIFICATE-----'
